import { data } from "@/lib/store";
import { requireSession } from "@/lib/auth";
import { Card, CardContent } from "@/components/ui/card";
import { AlertsClient } from "./alerts-client";

export default function AlertsPage() {
  const sess = requireSession();
  const alerts = data.alerts(sess.orgId);
  const users = data.users(sess.orgId);
  return (
    <div className="space-y-4">
      <div>
        <h1 className="text-2xl md:text-3xl font-bold">Alerts</h1>
        <p className="text-muted-foreground text-sm">
          Prioritized operational alerts — generated by the system or created manually.
        </p>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        {(["critical", "high", "warning", "info"] as const).map((sev) => {
          const count = alerts.filter((a) => a.severity === sev && a.status === "open").length;
          return (
            <Card key={sev}>
              <CardContent className="p-4">
                <div className="text-xs uppercase tracking-wide text-muted-foreground">{sev}</div>
                <div className="mt-2 text-3xl font-bold tabular-nums">{count}</div>
                <div className="text-xs text-muted-foreground mt-1">open</div>
              </CardContent>
            </Card>
          );
        })}
      </div>

      <AlertsClient alerts={alerts} users={users} />
    </div>
  );
}
