"use client";

import { useState, useMemo } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input, Label } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Download } from "lucide-react";

export function ROICalculator() {
  const [sites, setSites] = useState(3);
  const [throughput, setThroughput] = useState(2000);
  const [downtimeCost, setDowntimeCost] = useState(2_400_000);
  const [avoidedDays, setAvoidedDays] = useState(7);
  const [tierMonthly, setTierMonthly] = useState(25000);

  const result = useMemo(() => {
    const screeningsPerYear = throughput * 365;
    const annualPlatformCost = tierMonthly * 12 * Math.max(1, Math.ceil(sites / 10));
    const protectedValue = downtimeCost * avoidedDays;
    const conservativeProtected = protectedValue * 0.4;
    const roi = ((conservativeProtected - annualPlatformCost) / annualPlatformCost) * 100;
    return {
      screeningsPerYear,
      annualPlatformCost,
      protectedValue,
      conservativeProtected,
      roi,
    };
  }, [sites, throughput, downtimeCost, avoidedDays, tierMonthly]);

  function downloadProposal() {
    const txt = `OutbreakOS — Proposal Summary

Sites protected: ${sites}
Daily workers / travelers screened (per site): ${throughput.toLocaleString()}
Screenings per year across all sites: ${(result.screeningsPerYear * sites).toLocaleString()}

Estimated cost of one day of unplanned shutdown: $${downtimeCost.toLocaleString()}
Days of shutdown OutbreakOS realistically helps avoid: ${avoidedDays}
Gross protected value: $${result.protectedValue.toLocaleString()}
Conservative protected value (40%): $${Math.round(result.conservativeProtected).toLocaleString()}

OutbreakOS platform cost (annual): $${result.annualPlatformCost.toLocaleString()}
Estimated ROI: ${result.roi.toFixed(0)}%

This is a planning estimate, not a guarantee. Generated by the OutbreakOS ROI calculator.
`;
    const blob = new Blob([txt], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "outbreakos-proposal.txt";
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="grid lg:grid-cols-2 gap-8">
      <Card>
        <CardHeader>
          <CardTitle>Inputs</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <Field label="Sites protected" value={sites} set={setSites} />
          <Field label="Workers / travelers screened per day (per site)" value={throughput} set={setThroughput} />
          <Field label="Cost of one day of unplanned shutdown ($)" value={downtimeCost} set={setDowntimeCost} />
          <Field label="Days of shutdown OutbreakOS realistically helps avoid" value={avoidedDays} set={setAvoidedDays} />
          <Field label="Selected tier monthly cost ($)" value={tierMonthly} set={setTierMonthly} />
        </CardContent>
      </Card>
      <Card className="bg-gradient-to-br from-card to-primary/5">
        <CardHeader>
          <CardTitle>Estimated impact</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <Row label="Screenings / year (per site)" value={result.screeningsPerYear.toLocaleString()} />
          <Row label="Total annual screenings" value={(result.screeningsPerYear * sites).toLocaleString()} />
          <Row label="Annual OutbreakOS cost" value={"$" + result.annualPlatformCost.toLocaleString()} />
          <Row label="Conservative protected value" value={"$" + Math.round(result.conservativeProtected).toLocaleString()} highlight />
          <Row label="Estimated ROI" value={result.roi.toFixed(0) + "%"} highlight />
          <Button onClick={downloadProposal} className="w-full mt-4" variant="outline">
            <Download className="h-4 w-4" /> Download proposal summary
          </Button>
          <p className="text-xs text-muted-foreground">
            Planning estimate, not a guarantee. Conservative protected value
            applies a 40% factor to the gross avoided downtime figure.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}

function Field({ label, value, set }: { label: string; value: number; set: (n: number) => void }) {
  return (
    <div className="space-y-1.5">
      <Label>{label}</Label>
      <Input
        type="number"
        value={value}
        onChange={(e) => set(Number(e.target.value) || 0)}
      />
    </div>
  );
}

function Row({ label, value, highlight }: { label: string; value: string; highlight?: boolean }) {
  return (
    <div className={"flex items-center justify-between py-2 " + (highlight ? "border-t border-border pt-3 text-lg font-semibold" : "")}>
      <span className={highlight ? "text-foreground" : "text-muted-foreground text-sm"}>{label}</span>
      <span className={highlight ? "text-primary" : "tabular-nums"}>{value}</span>
    </div>
  );
}
