"use client";

import { useState, useMemo } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input, Label, Select } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Download, Mail } from "lucide-react";
import { annualCost, recommendTier, TIERS, type TierId } from "@/lib/pricing";

export function ROICalculator() {
  const [sites, setSites] = useState(3);
  const [throughput, setThroughput] = useState(2000);
  const [downtimeCost, setDowntimeCost] = useState(2_400_000);
  const [avoidedDays, setAvoidedDays] = useState(7);
  const [tierId, setTierId] = useState<TierId>(recommendTier(3));
  const [contractYears, setContractYears] = useState(1);
  const [leadEmail, setLeadEmail] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [leadSaved, setLeadSaved] = useState(false);

  const result = useMemo(() => {
    const annualCostUsd = annualCost(tierId, sites);
    const screeningsPerYear = throughput * 365;
    const protectedValue = downtimeCost * avoidedDays;
    const conservativeProtected = protectedValue * 0.4;
    const roi = ((conservativeProtected - annualCostUsd) / annualCostUsd) * 100;
    return {
      screeningsPerYear,
      annualCostUsd,
      contractCost: annualCostUsd * contractYears,
      protectedValue,
      conservativeProtected,
      roi,
    };
  }, [sites, throughput, downtimeCost, avoidedDays, tierId, contractYears]);

  function downloadProposal() {
    const txt = `OutbreakOS — Proposal Summary

Tier: ${TIERS.find((t) => t.id === tierId)?.name}
Contract length: ${contractYears} year(s)
Sites covered: ${sites}
Daily workers / travelers screened per site: ${throughput.toLocaleString()}
Total annual screenings across all sites: ${(result.screeningsPerYear * sites).toLocaleString()}

Estimated cost of one day of unplanned shutdown: $${downtimeCost.toLocaleString()}
Days of shutdown OutbreakOS realistically helps avoid: ${avoidedDays}
Gross protected value: $${result.protectedValue.toLocaleString()}
Conservative protected value (40%): $${Math.round(result.conservativeProtected).toLocaleString()}

Annual subscription cost: $${result.annualCostUsd.toLocaleString()}
${contractYears > 1 ? `Total ${contractYears}-year cost: $${result.contractCost.toLocaleString()}` : ""}
Estimated ROI: ${result.roi.toFixed(0)}%

This is a planning estimate, not a guarantee. Generated by the OutbreakOS ROI
calculator. To discuss, reach the OutbreakOS team via the /contact page.
`;
    const blob = new Blob([txt], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "outbreakos-proposal.txt";
    a.click();
    URL.revokeObjectURL(url);
  }

  async function saveAsLead() {
    if (!leadEmail) return;
    setSubmitting(true);
    await fetch("/api/leads", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        email: leadEmail,
        intent: "pilot",
        source: "roi-calculator",
        message: `ROI scenario: ${sites} sites, ${throughput}/day, $${downtimeCost.toLocaleString()}/day shutdown, ${avoidedDays}d avoided, tier=${tierId}. Estimated ROI ${result.roi.toFixed(0)}%.`,
      }),
    });
    setSubmitting(false);
    setLeadSaved(true);
    setTimeout(() => setLeadSaved(false), 3000);
  }

  return (
    <div className="grid lg:grid-cols-2 gap-8">
      <Card>
        <CardHeader>
          <CardTitle>Inputs</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <Field label="Sites protected" value={sites} set={(n) => {
            setSites(n);
            setTierId(recommendTier(n));
          }} />
          <Field
            label="Workers / travelers screened per day (per site)"
            value={throughput}
            set={setThroughput}
          />
          <Field
            label="Cost of one day of unplanned shutdown ($)"
            value={downtimeCost}
            set={setDowntimeCost}
          />
          <Field
            label="Days of shutdown OutbreakOS realistically helps avoid"
            value={avoidedDays}
            set={setAvoidedDays}
          />
          <div className="space-y-1.5">
            <Label>Tier</Label>
            <Select value={tierId} onChange={(e) => setTierId(e.target.value as TierId)}>
              {TIERS.map((t) => (
                <option key={t.id} value={t.id}>
                  {t.name}
                </option>
              ))}
            </Select>
            <p className="text-[11px] text-muted-foreground">
              {TIERS.find((t) => t.id === tierId)?.description}
            </p>
          </div>
          <Field label="Contract length (years)" value={contractYears} set={setContractYears} />
        </CardContent>
      </Card>
      <Card className="bg-gradient-to-br from-card to-primary/5">
        <CardHeader>
          <CardTitle>Estimated impact</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <Row
            label="Screenings / year (per site)"
            value={result.screeningsPerYear.toLocaleString()}
          />
          <Row
            label="Total annual screenings"
            value={(result.screeningsPerYear * sites).toLocaleString()}
          />
          <Row
            label="Annual OutbreakOS cost"
            value={"$" + result.annualCostUsd.toLocaleString()}
          />
          {contractYears > 1 && (
            <Row
              label={`${contractYears}-year contract cost`}
              value={"$" + result.contractCost.toLocaleString()}
            />
          )}
          <Row
            label="Conservative protected value"
            value={"$" + Math.round(result.conservativeProtected).toLocaleString()}
            highlight
          />
          <Row label="Estimated ROI" value={result.roi.toFixed(0) + "%"} highlight />
          <Button onClick={downloadProposal} className="w-full mt-4" variant="outline">
            <Download className="h-4 w-4" /> Download proposal summary
          </Button>
          <div className="rounded-md border border-border bg-card p-3 mt-3 space-y-2">
            <Label>Send to my email and a human will reach out</Label>
            <div className="flex gap-2">
              <Input
                type="email"
                placeholder="you@company.com"
                value={leadEmail}
                onChange={(e) => setLeadEmail(e.target.value)}
              />
              <Button onClick={saveAsLead} disabled={submitting || !leadEmail}>
                <Mail className="h-4 w-4" /> Send
              </Button>
            </div>
            {leadSaved && (
              <p className="text-xs text-[hsl(var(--success))]">
                Saved. We'll be in touch within one business day.
              </p>
            )}
          </div>
          <p className="text-xs text-muted-foreground">
            Planning estimate, not a guarantee. Conservative protected value
            applies a 40% factor to the gross avoided-downtime figure. Pricing
            uses the same function as the /pricing page.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}

function Field({
  label,
  value,
  set,
}: {
  label: string;
  value: number;
  set: (n: number) => void;
}) {
  return (
    <div className="space-y-1.5">
      <Label>{label}</Label>
      <Input
        type="number"
        value={value}
        onChange={(e) => set(Number(e.target.value) || 0)}
      />
    </div>
  );
}

function Row({
  label,
  value,
  highlight,
}: {
  label: string;
  value: string;
  highlight?: boolean;
}) {
  return (
    <div
      className={
        "flex items-center justify-between py-2 " +
        (highlight ? "border-t border-border pt-3 text-lg font-semibold" : "")
      }
    >
      <span className={highlight ? "text-foreground" : "text-muted-foreground text-sm"}>
        {label}
      </span>
      <span className={highlight ? "text-primary" : "tabular-nums"}>{value}</span>
    </div>
  );
}
