import type {
  Alert,
  AuditEvent,
  CaseRecord,
  Contact,
  Organization,
  OrgSettings,
  OutbreakRegion,
  Profile,
  ResourceItem,
  ScreeningRecord,
  Site,
  SitRep,
} from "./types";

// Seeded operational demo data for the bundled DRC / Uganda Bundibugyo
// outbreak scenario. Every record below carries the DEMO_FLAG so the UI can
// clearly label it as illustrative.

export const DEMO_FLAG = "demo";

export const DEMO_ORG: Organization = {
  id: "org_demo",
  name: "Sentinel Response Coalition",
  slug: "sentinel-response",
  mode: "gov_emergency",
  branding: { primary: "#38bdf8", logoText: "OutbreakOS" },
  createdAt: "2026-05-01T08:00:00Z",
};

export const DEMO_USERS: Profile[] = [
  {
    id: "u_owner",
    orgId: DEMO_ORG.id,
    email: "demo@outbreakos.io",
    name: "Dr. Amara Okonkwo",
    role: "owner",
    createdAt: "2026-05-01T08:00:00Z",
  },
  {
    id: "u_admin",
    orgId: DEMO_ORG.id,
    email: "admin@outbreakos.io",
    name: "Tomas Berhane",
    role: "admin",
    createdAt: "2026-05-01T08:00:00Z",
  },
  {
    id: "u_ho",
    orgId: DEMO_ORG.id,
    email: "ho@outbreakos.io",
    name: "Dr. Grace Mwende",
    role: "health_officer",
    createdAt: "2026-05-01T08:00:00Z",
  },
  {
    id: "u_screener",
    orgId: DEMO_ORG.id,
    email: "screener@outbreakos.io",
    name: "Joseph Kato",
    role: "screener",
    siteId: "site_entebbe",
    createdAt: "2026-05-01T08:00:00Z",
  },
  {
    id: "u_viewer",
    orgId: DEMO_ORG.id,
    email: "viewer@outbreakos.io",
    name: "Investor Demo",
    role: "viewer",
    createdAt: "2026-05-01T08:00:00Z",
  },
];

export const DEMO_SITES: Site[] = [
  {
    id: "site_entebbe",
    orgId: DEMO_ORG.id,
    name: "Entebbe International Airport",
    kind: "airport",
    country: "Uganda",
    region: "Wakiso",
    lat: 0.0424,
    lng: 32.4435,
    workersPerDay: 4200,
    status: "active",
  },
  {
    id: "site_bunia",
    orgId: DEMO_ORG.id,
    name: "Bunia Airport Checkpoint",
    kind: "airport",
    country: "DRC",
    region: "Ituri",
    lat: 1.5658,
    lng: 30.221,
    workersPerDay: 800,
    status: "monitoring",
  },
  {
    id: "site_bundibugyo",
    orgId: DEMO_ORG.id,
    name: "Bundibugyo District Hospital",
    kind: "hospital",
    country: "Uganda",
    region: "Bundibugyo",
    lat: 0.7117,
    lng: 30.0639,
    status: "monitoring",
  },
  {
    id: "site_kasese_border",
    orgId: DEMO_ORG.id,
    name: "Mpondwe / Kasese Border Post",
    kind: "border",
    country: "Uganda",
    region: "Kasese",
    lat: 0.2156,
    lng: 29.9586,
    workersPerDay: 2300,
    status: "active",
  },
  {
    id: "site_kilo_mine",
    orgId: DEMO_ORG.id,
    name: "Kilo-Moto Gold Operation",
    kind: "mine",
    country: "DRC",
    region: "Ituri",
    lat: 1.85,
    lng: 30.18,
    workersPerDay: 1800,
    status: "monitoring",
  },
  {
    id: "site_ngo_basecamp",
    orgId: DEMO_ORG.id,
    name: "NGO Field Coordination Base",
    kind: "field_base",
    country: "DRC",
    region: "North Kivu",
    lat: -1.65,
    lng: 29.22,
    status: "active",
  },
];

export const DEMO_REGIONS: OutbreakRegion[] = [
  {
    id: "reg_bundibugyo",
    orgId: "org_demo",
    name: "Bundibugyo District",
    country: "Uganda",
    lat: 0.7117,
    lng: 30.0639,
    radiusKm: 45,
    confirmed: 14,
    suspected: 23,
    deaths: 3,
    contactsMonitored: 187,
    severity: "high",
    trend: "rising",
    updatedAt: "2026-05-21T18:00:00Z",
  },
  {
    id: "reg_kasese",
    orgId: "org_demo",
    name: "Kasese District",
    country: "Uganda",
    lat: 0.1833,
    lng: 30.0833,
    radiusKm: 60,
    confirmed: 4,
    suspected: 9,
    deaths: 0,
    contactsMonitored: 62,
    severity: "warning",
    trend: "stable",
    updatedAt: "2026-05-21T18:00:00Z",
  },
  {
    id: "reg_ituri",
    orgId: "org_demo",
    name: "Ituri Province",
    country: "DRC",
    lat: 1.5,
    lng: 29.5,
    radiusKm: 120,
    confirmed: 6,
    suspected: 18,
    deaths: 1,
    contactsMonitored: 94,
    severity: "high",
    trend: "rising",
    updatedAt: "2026-05-21T18:00:00Z",
  },
  {
    id: "reg_north_kivu",
    orgId: "org_demo",
    name: "North Kivu",
    country: "DRC",
    lat: -0.7,
    lng: 29.2,
    radiusKm: 140,
    confirmed: 2,
    suspected: 7,
    deaths: 0,
    contactsMonitored: 31,
    severity: "warning",
    trend: "stable",
    updatedAt: "2026-05-21T18:00:00Z",
  },
];

export const DEMO_CASES: CaseRecord[] = [
  {
    id: "case_001",
    orgId: DEMO_ORG.id,
    classification: "confirmed",
    outcome: "monitoring",
    regionId: "reg_bundibugyo",
    reportedAt: "2026-05-12T10:00:00Z",
    notes: "Index case; community transmission suspected.",
  },
  {
    id: "case_002",
    orgId: DEMO_ORG.id,
    classification: "confirmed",
    outcome: "deceased",
    regionId: "reg_bundibugyo",
    reportedAt: "2026-05-14T09:00:00Z",
    notes: "Funeral attendance traced to 28 contacts.",
  },
  {
    id: "case_003",
    orgId: DEMO_ORG.id,
    classification: "probable",
    outcome: "monitoring",
    regionId: "reg_ituri",
    reportedAt: "2026-05-18T11:00:00Z",
    notes: "Cross-border traveler from Bundibugyo.",
  },
  {
    id: "case_004",
    orgId: DEMO_ORG.id,
    classification: "suspected",
    outcome: "monitoring",
    regionId: "reg_kasese",
    reportedAt: "2026-05-20T15:30:00Z",
    notes: "Healthcare worker contact, awaiting lab.",
  },
];

const today = new Date("2026-05-22T12:00:00Z");
function daysAgo(n: number) {
  return new Date(today.getTime() - n * 86400000).toISOString();
}

export const DEMO_SCREENINGS: ScreeningRecord[] = [
  {
    id: "scr_001",
    orgId: DEMO_ORG.id,
    siteId: "site_entebbe",
    context: "airport",
    subjectName: "Anonymous-EBB-4821",
    anonymous: true,
    ageRange: "18-39",
    originCountry: "DRC",
    originRegion: "Ituri",
    destination: "Kampala",
    travelHistory: ["Bunia", "Goma", "Kampala"],
    contactWithCase: true,
    symptoms: {
      fever: true,
      vomitingDiarrhea: false,
      unexplainedBleeding: false,
      fatigue: true,
      headache: true,
    },
    hcwExposure: false,
    funeralExposure: true,
    notes: "Reports attending family burial in Bunia 9 days ago.",
    risk: "urgent",
    action:
      "Isolate immediately in designated area and notify the on-call health officer.",
    rationale: [
      "Reported fever (+25)",
      "Funeral / burial exposure (+20)",
      "Reported contact with suspected/confirmed case (+30)",
      "Travel through active outbreak region (+20)",
    ],
    createdAt: daysAgo(0),
    createdBy: "u_screener",
  },
  {
    id: "scr_002",
    orgId: DEMO_ORG.id,
    siteId: "site_kilo_mine",
    context: "site_entry",
    subjectName: "Worker-KM-1142",
    anonymous: true,
    ageRange: "40-59",
    originCountry: "DRC",
    originRegion: "Ituri",
    destination: "Kilo-Moto site",
    travelHistory: ["Bunia"],
    contactWithCase: false,
    symptoms: {
      fever: false,
      vomitingDiarrhea: false,
      unexplainedBleeding: false,
      fatigue: true,
      headache: false,
    },
    hcwExposure: false,
    funeralExposure: false,
    notes: "Returning from off-rotation leave.",
    risk: "monitor",
    action: "Clear for entry; enroll in 21-day daily symptom check-in.",
    rationale: ["Fatigue (+5)", "Origin in active outbreak region (+15)"],
    createdAt: daysAgo(1),
    createdBy: "u_screener",
  },
  {
    id: "scr_003",
    orgId: DEMO_ORG.id,
    siteId: "site_bundibugyo",
    context: "clinic",
    subjectName: "Patient-BBG-7732",
    anonymous: true,
    ageRange: "60+",
    originCountry: "Uganda",
    originRegion: "Bundibugyo",
    destination: "Bundibugyo District Hospital",
    travelHistory: ["Bundibugyo"],
    contactWithCase: true,
    symptoms: {
      fever: true,
      vomitingDiarrhea: true,
      unexplainedBleeding: true,
      fatigue: true,
      headache: true,
    },
    hcwExposure: true,
    funeralExposure: false,
    notes: "Family of confirmed case_002.",
    risk: "urgent",
    action: "Isolate immediately; notify health officer; lab sample queued.",
    rationale: [
      "Reported fever (+25)",
      "Vomiting / diarrhea (+15)",
      "Unexplained bleeding (+40)",
      "Reported contact with suspected/confirmed case (+30)",
      "Healthcare worker exposure (+15)",
    ],
    createdAt: daysAgo(2),
    createdBy: "u_screener",
  },
  {
    id: "scr_004",
    orgId: DEMO_ORG.id,
    siteId: "site_kasese_border",
    context: "site_entry",
    subjectName: "Anonymous-KSE-2210",
    anonymous: true,
    ageRange: "18-39",
    originCountry: "DRC",
    originRegion: "North Kivu",
    destination: "Kasese, Uganda",
    travelHistory: ["Goma", "Mpondwe"],
    contactWithCase: false,
    symptoms: {
      fever: false,
      vomitingDiarrhea: false,
      unexplainedBleeding: false,
      fatigue: false,
      headache: false,
    },
    hcwExposure: false,
    funeralExposure: false,
    notes: "Routine cross-border trader.",
    risk: "low",
    action: "Clear for entry.",
    rationale: ["No risk factors reported."],
    createdAt: daysAgo(3),
    createdBy: "u_screener",
  },
];

export const DEMO_CONTACTS: Contact[] = [
  {
    id: "ct_001",
    orgId: DEMO_ORG.id,
    name: "Contact-BBG-A1",
    phone: "+256700000001",
    linkedCaseId: "case_002",
    monitoringStart: daysAgo(8),
    monitoringEnd: daysAgo(-13),
    status: "active",
    checkins: Array.from({ length: 9 }, (_, i) => ({
      day: i + 1,
      date: daysAgo(8 - i),
      status: i === 5 ? "missed" : i === 7 ? "symptom" : "ok",
    })),
    notes: "Sister of confirmed case_002. SMS check-in active.",
  },
  {
    id: "ct_002",
    orgId: DEMO_ORG.id,
    name: "Contact-BBG-A2",
    phone: "+256700000002",
    linkedCaseId: "case_002",
    monitoringStart: daysAgo(8),
    monitoringEnd: daysAgo(-13),
    status: "escalated",
    checkins: Array.from({ length: 9 }, (_, i) => ({
      day: i + 1,
      date: daysAgo(8 - i),
      status: i >= 6 ? "symptom" : "ok",
    })),
    notes: "Developed fever on day 7. Referred to Bundibugyo District Hospital.",
  },
  {
    id: "ct_003",
    orgId: DEMO_ORG.id,
    name: "Contact-ITU-B1",
    phone: "+243800000003",
    linkedScreeningId: "scr_001",
    monitoringStart: daysAgo(0),
    monitoringEnd: daysAgo(-21),
    status: "active",
    checkins: [{ day: 1, date: daysAgo(0), status: "ok" }],
    notes: "Enrolled today from Entebbe screening.",
  },
  {
    id: "ct_004",
    orgId: DEMO_ORG.id,
    name: "Contact-KM-C9",
    phone: "+243800000004",
    monitoringStart: daysAgo(15),
    monitoringEnd: daysAgo(-6),
    status: "cleared",
    checkins: Array.from({ length: 21 }, (_, i) => ({
      day: i + 1,
      date: daysAgo(15 - i),
      status: "ok" as const,
    })),
    notes: "Completed 21-day window symptom-free.",
  },
  {
    id: "ct_005",
    orgId: DEMO_ORG.id,
    name: "Contact-NK-D2",
    phone: "+243800000005",
    monitoringStart: daysAgo(12),
    monitoringEnd: daysAgo(-9),
    status: "lost_to_follow_up",
    checkins: Array.from({ length: 12 }, (_, i) => ({
      day: i + 1,
      date: daysAgo(12 - i),
      status: i >= 5 ? "missed" : "ok",
    })),
    notes: "Missed 7 consecutive check-ins. Field team dispatched.",
  },
];

export const DEMO_ALERTS: Alert[] = [
  {
    id: "al_001",
    orgId: DEMO_ORG.id,
    category: "high_risk_screening",
    severity: "critical",
    title: "Urgent escalation — Entebbe Airport",
    description:
      "Traveler from Bunia with fever, funeral exposure, and contact history flagged urgent at gate B12.",
    status: "open",
    owner: "u_ho",
    linkedId: "scr_001",
    createdAt: daysAgo(0),
  },
  {
    id: "al_002",
    orgId: DEMO_ORG.id,
    category: "cluster_increase",
    severity: "high",
    title: "Bundibugyo cluster — +6 suspected in 48h",
    description:
      "Bundibugyo District suspected cases up 36% in 48 hours; trend rising.",
    status: "ack",
    owner: "u_ho",
    linkedId: "reg_bundibugyo",
    createdAt: daysAgo(1),
  },
  {
    id: "al_003",
    orgId: DEMO_ORG.id,
    category: "missed_checkin",
    severity: "warning",
    title: "Contact-BBG-A1 missed day-6 check-in",
    description:
      "No SMS response on day 6 of 21-day monitoring. Auto-retry scheduled.",
    status: "open",
    linkedId: "ct_001",
    createdAt: daysAgo(2),
  },
  {
    id: "al_004",
    orgId: DEMO_ORG.id,
    category: "ppe_low_stock",
    severity: "warning",
    title: "PPE kits below threshold — Bundibugyo District Hospital",
    description:
      "Full PPE kits at 32 units (min 50). Burn rate suggests 4 days of cover.",
    status: "open",
    owner: "u_admin",
    linkedId: "site_bundibugyo",
    createdAt: daysAgo(1),
  },
  {
    id: "al_005",
    orgId: DEMO_ORG.id,
    category: "border_risk",
    severity: "high",
    title: "Mpondwe border — surge in symptomatic crossings",
    description:
      "12 elevated-risk screenings in last 24h at Mpondwe/Kasese border post.",
    status: "open",
    linkedId: "site_kasese_border",
    createdAt: daysAgo(0),
  },
  {
    id: "al_006",
    orgId: DEMO_ORG.id,
    category: "lab_pending",
    severity: "info",
    title: "3 lab samples pending — case_004 cohort",
    description: "Samples in transit to Uganda Virus Research Institute.",
    status: "ack",
    linkedId: "case_004",
    createdAt: daysAgo(1),
  },
];

export const DEMO_RESOURCES: ResourceItem[] = [
  {
    id: "r_001",
    orgId: DEMO_ORG.id,
    siteId: "site_bundibugyo",
    category: "ppe_kit",
    label: "Full PPE Kit (Tier 3)",
    onHand: 32,
    minStock: 50,
    burnRatePerDay: 8,
    unit: "kits",
  },
  {
    id: "r_002",
    orgId: DEMO_ORG.id,
    siteId: "site_bundibugyo",
    category: "gloves",
    label: "Nitrile Gloves",
    onHand: 4800,
    minStock: 3000,
    burnRatePerDay: 220,
    unit: "pairs",
  },
  {
    id: "r_003",
    orgId: DEMO_ORG.id,
    siteId: "site_bundibugyo",
    category: "gowns",
    label: "Disposable Gowns",
    onHand: 410,
    minStock: 200,
    burnRatePerDay: 40,
    unit: "gowns",
  },
  {
    id: "r_004",
    orgId: DEMO_ORG.id,
    siteId: "site_bundibugyo",
    category: "masks",
    label: "N95 Respirators",
    onHand: 720,
    minStock: 500,
    burnRatePerDay: 65,
    unit: "masks",
  },
  {
    id: "r_005",
    orgId: DEMO_ORG.id,
    siteId: "site_bundibugyo",
    category: "sample_kits",
    label: "Sample Collection Kits",
    onHand: 38,
    minStock: 60,
    burnRatePerDay: 6,
    unit: "kits",
  },
  {
    id: "r_006",
    orgId: DEMO_ORG.id,
    siteId: "site_bundibugyo",
    category: "disinfectant",
    label: "Chlorine Solution 0.5%",
    onHand: 240,
    minStock: 150,
    burnRatePerDay: 22,
    unit: "L",
  },
  {
    id: "r_007",
    orgId: DEMO_ORG.id,
    siteId: "site_bundibugyo",
    category: "beds",
    label: "Isolation Beds",
    onHand: 12,
    minStock: 10,
    burnRatePerDay: 0,
    unit: "beds",
  },
  {
    id: "r_008",
    orgId: DEMO_ORG.id,
    siteId: "site_bundibugyo",
    category: "staff",
    label: "Available Trained Staff",
    onHand: 18,
    minStock: 20,
    burnRatePerDay: 0,
    unit: "people",
  },
  {
    id: "r_009",
    orgId: DEMO_ORG.id,
    siteId: "site_entebbe",
    category: "ppe_kit",
    label: "Screener PPE (Tier 1)",
    onHand: 410,
    minStock: 200,
    burnRatePerDay: 28,
    unit: "kits",
  },
  {
    id: "r_010",
    orgId: DEMO_ORG.id,
    siteId: "site_entebbe",
    category: "vehicles",
    label: "Isolation Transport Vehicles",
    onHand: 3,
    minStock: 2,
    burnRatePerDay: 0,
    unit: "vehicles",
  },
  {
    id: "r_011",
    orgId: DEMO_ORG.id,
    siteId: "site_kilo_mine",
    category: "ppe_kit",
    label: "Worker Screening PPE",
    onHand: 180,
    minStock: 120,
    burnRatePerDay: 14,
    unit: "kits",
  },
];

export const DEMO_REPORTS: SitRep[] = [
  {
    id: "rpt_001",
    orgId: DEMO_ORG.id,
    kind: "daily_sitrep",
    title: "Daily SITREP — 22 May 2026",
    generatedAt: daysAgo(0),
    generatedBy: "u_ho",
    aiAssisted: true,
    summary:
      "Cross-border Bundibugyo cluster continues rising trend with 6 new suspected cases in 48h. Entebbe Airport intercepted one urgent-risk traveler today. PPE stock at Bundibugyo District Hospital projects 4 days of cover at current burn rate.",
    keyNumbers: [
      { label: "Confirmed cases", value: "26", delta: "+3 (48h)" },
      { label: "Suspected cases", value: "57", delta: "+6 (48h)" },
      { label: "Deaths", value: "4", delta: "+1 (48h)" },
      { label: "Contacts monitored", value: "374", delta: "+18 (48h)" },
      { label: "Screenings (24h)", value: "1,842", delta: "+9%" },
      { label: "Urgent escalations (24h)", value: "3", delta: "+2" },
    ],
    hotspots: [
      "Bundibugyo District (Uganda) — rising",
      "Ituri Province (DRC) — rising",
      "Kasese border crossings — surveillance",
    ],
    openRisks: [
      "PPE stock at Bundibugyo District Hospital below threshold",
      "Mpondwe border surge in symptomatic crossings",
      "1 contact lost to follow-up in North Kivu",
    ],
    recommended: [
      "Pre-position 80 PPE kits to Bundibugyo within 48h",
      "Activate secondary screening lane at Mpondwe border",
      "Dispatch field team to recover lost contact in North Kivu",
      "Initiate joint UG/DRC daily coordination call",
    ],
    changesSinceLast: [
      "New confirmed case in Bundibugyo (case_005 pending)",
      "Lab results expected for case_004 within 24h",
      "Two contacts cleared from 21-day monitoring window",
    ],
  },
  {
    id: "rpt_002",
    orgId: DEMO_ORG.id,
    kind: "airport_screening",
    title: "Airport Screening Report — Entebbe — 22 May 2026",
    generatedAt: daysAgo(0),
    generatedBy: "u_ho",
    aiAssisted: true,
    summary:
      "Entebbe screened 1,402 travelers in the last 24h. 38 were enrolled in monitoring (low/monitor tier). 1 traveler escalated as urgent — currently isolated pending health-authority handover.",
    keyNumbers: [
      { label: "Travelers screened", value: "1,402" },
      { label: "Cleared (low)", value: "1,361" },
      { label: "Monitor", value: "38" },
      { label: "Elevated", value: "2" },
      { label: "Urgent", value: "1" },
    ],
    hotspots: ["Gate B12 — Bunia inbound flights"],
    openRisks: ["Surge expected on UR-204 inbound 18:30"],
    recommended: [
      "Add 1 secondary screener to gate B12 evening shift",
      "Pre-brief ground crew on isolation pathway",
    ],
    changesSinceLast: [
      "Throughput +9% vs yesterday",
      "Average screening time 4m 12s (down from 4m 41s)",
    ],
  },
];

export const DEMO_AUDIT: AuditEvent[] = [
  {
    id: "a_001",
    orgId: DEMO_ORG.id,
    actor: "u_screener",
    action: "screening.create",
    target: "scr_001",
    createdAt: daysAgo(0),
  },
  {
    id: "a_002",
    orgId: DEMO_ORG.id,
    actor: "system",
    action: "alert.create",
    target: "al_001",
    createdAt: daysAgo(0),
  },
  {
    id: "a_003",
    orgId: DEMO_ORG.id,
    actor: "u_ho",
    action: "alert.ack",
    target: "al_002",
    createdAt: daysAgo(1),
  },
  {
    id: "a_004",
    orgId: DEMO_ORG.id,
    actor: "u_ho",
    action: "report.generate",
    target: "rpt_001",
    createdAt: daysAgo(0),
  },
  {
    id: "a_005",
    orgId: DEMO_ORG.id,
    actor: "u_admin",
    action: "resource.update",
    target: "r_001",
    createdAt: daysAgo(1),
  },
];

export const DEMO_SETTINGS: OrgSettings = {
  orgId: DEMO_ORG.id,
  aiProvider: "none",
  messagingProvider: "none",
  riskWeights: {
    fever: 25,
    bleeding: 40,
    contact: 30,
    travel: 20,
    hcw: 15,
    funeral: 20,
  },
  apiKeysMasked: [
    { name: "Reporting Webhook", lastFour: "9f2c" },
    { name: "Lab Integration", lastFour: "11ab" },
  ],
};

// Screening time-series for dashboard chart
export const DEMO_TIMESERIES = (() => {
  const points: { date: string; screenings: number; flagged: number }[] = [];
  for (let i = 13; i >= 0; i--) {
    const base = 1100 + Math.round(Math.sin(i * 0.7) * 180) + (13 - i) * 18;
    const flagged = 20 + Math.round(Math.sin(i * 0.4) * 8) + (13 - i);
    points.push({
      date: daysAgo(i).slice(5, 10),
      screenings: base,
      flagged,
    });
  }
  return points;
})();

export const DEMO_RISK_BREAKDOWN = [
  { name: "Low", value: 1361, fill: "hsl(142 70% 45%)" },
  { name: "Monitor", value: 38, fill: "hsl(199 89% 48%)" },
  { name: "Elevated", value: 2, fill: "hsl(38 92% 50%)" },
  { name: "Urgent", value: 1, fill: "hsl(0 84% 60%)" },
];
